import type { Metadata } from "next";
import { View } from "reshaped";
import App from "@/components/App";
import Menu from "@/components/Menu";
import Submenu from "@/components/Submenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-rs-theme="reshaped" data-rs-color-mode="dark">
      <body>
        <App>
          <View direction="row" divided height="100dvh" align="stretch">
            <View
              backgroundColor="elevation-base"
              divided
              direction="row"
              align="stretch"
            >
              <Menu />
              <Submenu />
            </View>
            <View.Item>{children}</View.Item>
          </View>
        </App>
      </body>
    </html>
  );
}
